PATCH http://{{host-url}}/cart
accept: text/plain
x-session-id: {{session-id}}
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "value": { "sku" : "abc-100", "quantity": 2 , "amount": 20.98 } ,
    "path": "/0"
  },
  {
    "op": "add",
    "value": { "sku" : "abc-200", "quantity": 3, "amount": 31.99 } ,
    "path": "/-"
  }
]