PATCH http://localhost:5001/cart
accept: text/plain
x-session-id: 3E520260-2CB4-462A-BA04-C2F7CFAB1EFE
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "value": { "sku" : "abc-100", "quantity": 1 } ,
    "path": "/-"
  },
  {
    "op": "add",
    "value": { "sku" : "abc-200", "quantity": 3 } ,
    "path": "/-"
  }
]