## Post Cart Item 
POST http://{{host-url}}/cart
accept: application/json
x-session-id: {{create-session-id}}
Content-Type: application/json-patch+json

[
  {
    "sku": "abc-100",
    "quantity": 2,
    "amount": 9.99
  }
]

> {% 
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
        });
 %}
###

## Get
GET http://{{host-url}}/cart
accept: application/json
x-session-id: {{create-session-id}}

> {% 
 client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
 %}
###