apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cart-service
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: keyPrefix
      value: name
    - name: host
      value: localhost:27017
    - name: username
      value: dapr
    - name: password
      value: daprPassword 
    - name: databaseName
      value: admin
    - name: collectionName
      value: cart 
  scopes:
   - cart-service